### ISSUE TITLE
Consider using react-virtualized

### ISSUE THREAD

**Issue by homerchen19** [Yoctol/tailor-ui#12]
just want to make a suggestion 🙋‍♂️
[react-virtualized](https://github.com/bvaughn/react-virtualized) is helpful for rendering a large list or a huge table efficiently. It could improve rendering performance, so maybe you can use it to implement `<Table>`, `<List>`, etc.

references
- http://blog.theodo.fr/2018/09/use-react-virtualized/
- https://blog.logrocket.com/rendering-large-lists-with-react-virtualized-82741907a6b3

**Comment by jigsawye** [comment]
I will take a look, maybe you can send a PR ❤️

**Comment by homerchen19** [comment]
`react-window` is better. #429 Good job!
