### ISSUE TITLE
mention 沒有高度

### ISSUE THREAD

**Issue by kpman** [Yoctol/tailor-ui#120]
![Screenshot 2019-03-25 15 36 16](https://user-images.githubusercontent.com/2382594/54902243-d18a8580-4f13-11e9-8bd5-8885e0f3e299.png)
![Kapture 2019-03-25 at 16 15 08](https://user-images.githubusercontent.com/2382594/54904340-34cae680-4f19-11e9-809c-63934b6dcaef.gif)

Firefox 67.0b4 (64-bit)

不是每次都會出現，但是出現機率不小

**Comment by jigsawye** [comment]
感覺跟 #121 有關係

**Comment by jigsawye** [comment]
@kpman 這個還有出現嗎

**Comment by kpman** [comment]
Firefox 很常出現，Chrome 不確定

**Comment by kpman** [comment]
![Screenshot 2019-03-28 14 56 50](https://user-images.githubusercontent.com/2382594/55136569-ba44d580-5169-11e9-8e3e-bb02b3dbf9be.png)
每開必出現

**Comment by jigsawye** [comment]
Can not reproduce
