### ISSUE TITLE
上傳元件，上傳時的「移除檔案」，點擊後應該要取消上傳

### ISSUE THREAD

**Issue by qshiwu** [Yoctol/tailor-ui#22]
現在上傳中點了「移除檔案」，一樣會上傳完畢
![kapture 2018-12-18 at 17 07 05](https://user-images.githubusercontent.com/662387/50143649-2486e800-02e8-11e9-8457-11bb10b3266c.gif)

**Comment by jigsawye** [comment]
這個之後要重新設計 flow 再重寫過

**Comment by jigsawye** [comment]
resolved
