### ISSUE TITLE
children type

### ISSUE THREAD

**Issue by homerchen19** [Yoctol/tailor-ui#30]
哈囉新年快樂 🎆 
我只是好奇為什麼 `children` 的 type 是 `JSX.Element` 而不是 `React.ReactNode`
雖然整個 repo 也只出現兩次而已～在[這](https://github.com/Yoctol/tailor-ui/blob/f3fba8dbb05f3f88d0bb76454fcee297db0f343a/src/UIProvider/UIProvider.tsx#L19)跟[這](https://github.com/Yoctol/tailor-ui/blob/490704c85a2b17bb714c5d651236039abb9a7338/docz/DoczWrapper.tsx#L6)

reference:
[sw-yx/react-typescript-cheatsheet#useful-react-prop-type-examples](https://github.com/sw-yx/react-typescript-cheatsheet#useful-react-prop-type-examples)
[DefinitelyTyped/blob/master/types/react/index.d.ts#L464](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L464)

**Comment by jigsawye** [comment]
小時候不懂事 Code 亂寫 QQ
