### ISSUE TITLE
[Proposal] 在 Doc page 可以複製 Colors value 

### ISSUE THREAD

**Issue by homerchen19** [Yoctol/tailor-ui#410]
哈囉～我覺得這樣好像能有更好的 UX，你們覺得呢

我先做了一版，如果覺得可以的話我再發 PR
如果不需要就直接 close issue 👍 

![Kapture 2020-01-31 at 23 39 42](https://user-images.githubusercontent.com/12113222/73548145-9f2aac80-4483-11ea-98b4-22b9e4878230.gif)

**Comment by jigsawye** [comment]
敲碗

**Comment by homerchen19** [comment]
電腦放在家，之前沒有先 push QQ
只能下班回家再 push 了 拍謝
