### ISSUE TITLE
mention 當有 error 狀態時，滑鼠 hover 可否維持邊框紅色

### ISSUE THREAD

**Issue by kpman** [Yoctol/tailor-ui#63]
![kapture 2019-02-19 at 10 28 49](https://user-images.githubusercontent.com/2382594/52985987-2d538180-3431-11e9-9dba-f8cb8de06f83.gif)

**Comment by jigsawye** [comment]
可

**Comment by kpman** [comment]
想要這個功能
有建議怎樣改嗎

**Comment by jigsawye** [comment]
舊的不改，新的可加

**Comment by jigsawye** [comment]
應該會跟 #71 一起考慮進去
