### ISSUE TITLE
refine upload message

### ISSUE THREAD

**Issue by chentsulin** [Yoctol/tailor-ui#90]
https://github.com/Yoctol/tailor-ui/issues/33
https://github.com/Yoctol/tailor-ui/search?q=upload+failure&unscoped_q=upload+failure

目前是這樣

```
Upload: {
  uploadText: 'Click to Upload',
  uploadingText: 'Uploading...',
  uploadedText: 'Upload Completed!',
  failureText: 'Upload Failure!',
}
```

uploaded 或 completed 應該要配 failed 不是 failure，所以 key 也有問題

https://github.com/Yoctol/kurator/issues/3218

點出了一些文案的問題

**Comment by jigsawye** [comment]
#91 先改字沒改 key

**Comment by jigsawye** [comment]
#101
